.catalog:
  name: "My Weeeeb Appp"
  version: "v0.1"
  description: "My Cooooooool App"
myweb-app:
  scale: 1
  load_balancer_config:
    haproxy_config: {}
  health_check:
    port: 42
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000
nginx-web-tier:
  scale: 1
